# Using Selenium IDE, Record the One Test
# open this → https://katalon-demo-cura.herokuapp.com/
# Click on the button Make appointment
# on the Next Page → Enter the username, password and submit button
# Export the script to Python.


import json
import time

# Generated by Selenium IDE
import pytest
from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait


class TestNegativetestcaseLoginpageCURAHealthcare():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_negativetestcase_Login_pageCURA_Healthcare(self):
        self.driver.get("https://katalon-demo-cura.herokuapp.com/")
        self.driver.set_window_size(1382, 744)
        self.driver.find_element(By.ID, "btn-make-appointment").click()
        self.driver.find_element(By.ID, "txt-username").click()
        self.driver.find_element(By.ID, "txt-username").send_keys("Varsha")
        self.driver.find_element(By.ID, "txt-password").click()
        self.driver.find_element(By.ID, "txt-password").send_keys("Cura@5035")
        self.driver.find_element(By.ID, "txt-password").send_keys(Keys.ENTER)
